name: Bug report
description: Things not quite working right
labels: 'bug'
body:
  - type: checkboxes
    attributes:
      options:
        - label: I have searched the [discussions](https://github.com/gitext-rs/git-fixture/discussions)
        - label: I have searched the existing issues
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Output of `git stack -V`
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: "For describing git state, see [`git-fixture`](../blob/main/CONTRIBUTING.md)"
  - type: textarea
    attributes:
      label: Actual Behaviour
      description: When I do like *this*, *that* is happening and I think it shouldn't.
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: I think *this* should happen instead.
  - type: textarea
    attributes:
      label: Debug Output
      description: Run with `-vv`
